openapi: 3.0.2
info:
  title: MTG Deck Building App Api
  version: 0.0.1
  contact:
    name: David Yell
    url: 'https://github.com/davidyell/Learning-Express-MTG-Api'
    email: neon1024@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3001'
paths:
  /api/decks:
    get:
      summary: List all available decks
      responses:
        '200':
          description: OK
      parameters: []
  '/api/decks/{deckId}':
    get:
      summary: View a specific deck
      parameters:
        - name: deckId
          in: path
          required: true
          description: The id of the deck to retrieve
          schema:
            type: number
      responses:
        '200':
          description: OK
        '404':
          description: Deck not found
externalDocs:
  url: 'https://github.com/davidyell/Learning-Express-MTG-Api'
security: []
components:
  links: {}
  callbacks: {}
  schemas: {}