openapi: 3.0.2
info:
  title: MTG Deck Building App Api
  version: 0.0.1
  contact:
    name: David Yell
    url: 'https://github.com/davidyell/Learning-Express-MTG-Api'
    email: neon1024@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3001'
paths:
  /api/decks:
    get:
      summary: List all available decks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      parameters: []
      tags:
        - decks
    post:
      summary: ''
      operationId: post-api-decks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    readOnly: true
                  player_id:
                    type: integer
                    readOnly: true
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                  updated:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                  - id
                  - name
                  - player_id
                  - created
                  - updated
      description: Create a new deck by posting the information about it
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                deck:
                  type: object
                  required:
                    - name
                    - player_id
                  additionalProperties: false
                  properties:
                    name:
                      type: string
                      writeOnly: true
                    player_id:
                      type: integer
                      writeOnly: true
                  writeOnly: true
                cards_in_decks:
                  type: array
                  items:
                    type: object
                    additionalProperties: false
                    properties:
                      card_id:
                        type: integer
                        writeOnly: true
                      quantity:
                        type: integer
                        writeOnly: true
                      is_sideboard:
                        type: boolean
                        default: false
                        writeOnly: true
                    required:
                      - card_id
                      - quantity
                      - is_sideboard
                    writeOnly: true
                  writeOnly: true
              required:
                - deck
                - cards_in_decks
              writeOnly: true
            examples: {}
        description: Create a new deck with a name and selection of cards
      parameters: []
      tags:
        - decks
  '/api/decks/{deckId}':
    get:
      summary: View a specific deck
      parameters:
        - name: deckId
          in: path
          required: true
          description: The id of the deck to retrieve
          schema:
            type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
        '404':
          description: Deck not found
          content:
            application/json:
              schema: {}
      tags:
        - decks
  '/api/cards/{cardId}':
    get:
      summary: View a certain cards details
      description: Provides a more in-depth set of data about a card
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
          description: The numerical id of the card to retrieve
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
        '404':
          description: Card not found
          content:
            application/json:
              schema: {}
      tags:
        - cards
  /api/players:
    get:
      summary: Get a list of all players
      description: ''
      parameters: []
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      tags:
        - players
  '/api/players/{playerId}':
    get:
      summary: View a single player
      description: ''
      parameters:
        - name: playerId
          in: path
          required: true
          schema:
            type: string
          description: Numerical id of the player
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
        '404':
          description: Player not found
          content:
            application/json:
              schema: {}
      tags:
        - players
security: []
components:
  links: {}
  callbacks: {}
  schemas: {}
  requestBodies:
    Create-deck:
      content:
        application/json:
          schema:
            type: object
            properties:
              deck:
                type: object
                properties:
                  name:
                    type: string
                  player_id:
                    type: integer
              cards_in_decks:
                type: array
                items:
                  type: object
                  properties:
                    card_id:
                      type: integer
                    quantity:
                      type: integer
                    is_sideboard:
                      type: boolean
            x-examples:
              example-1:
                deck:
                  name: Postman manual test - can create deck
                  player_id: 1
                cards_in_decks:
                  - card_id: 13422
                    quantity: 1
                    is_sideboard: false
                  - card_id: 13415
                    quantity: 1
                    is_sideboard: false
                  - card_id: 4503
                    quantity: 3
                    is_sideboard: false
                  - card_id: 34736
                    quantity: 3
                    is_sideboard: false
                  - card_id: 34733
                    quantity: 12
                    is_sideboard: false
                  - card_id: 13174
                    quantity: 4
                    is_sideboard: false
                  - card_id: 13167
                    quantity: 1
                    is_sideboard: false
                  - card_id: 13151
                    quantity: 3
                    is_sideboard: false
                  - card_id: 13308
                    quantity: 3
                    is_sideboard: false
                  - card_id: 13138
                    quantity: 1
                    is_sideboard: false
                  - card_id: 4581
                    quantity: 4
                    is_sideboard: false
                  - card_id: 4565
                    quantity: 4
                    is_sideboard: false
                  - card_id: 13164
                    quantity: 1
                    is_sideboard: false
                  - card_id: 13149
                    quantity: 2
                    is_sideboard: false
                  - card_id: 13163
                    quantity: 4
                    is_sideboard: false
                  - card_id: 40870
                    quantity: 4
                    is_sideboard: false
                  - card_id: 13168
                    quantity: 3
                    is_sideboard: false
                  - card_id: 40797
                    quantity: 2
                    is_sideboard: false
                  - card_id: 34765
                    quantity: 4
                    is_sideboard: false
                  - card_id: 34736
                    quantity: 1
                    is_sideboard: true
                  - card_id: 2844
                    quantity: 2
                    is_sideboard: true
                  - card_id: 4577
                    quantity: 2
                    is_sideboard: true
                  - card_id: 40886
                    quantity: 3
                    is_sideboard: true
                  - card_id: 4206
                    quantity: 3
                    is_sideboard: true
                  - card_id: 286
                    quantity: 4
                    is_sideboard: true
      description: Create a brand new deck for a player with a name and a selection of cards
