# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          # Set always-auth in npmrc.
          always-auth: false
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          check-latest: true
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: yarn

      - name: Setup the environment
        run: |
          echo PORT="3001" >> .env
          echo DATABASE_URL="file:${GITHUB_WORKSPACE}/infrastructure/database.sqlite" >> .env
          
      - name: Install dependencies
        run: yarn install
          
      - name: Setup the database & ORM
        run: |
          yarn prisma generate
          yarn prisma db push
      
      - name: Insert data into database
        run: |
          sqlite3 -init ${GITHUB_WORKSPACE}/infrastructure/sql/import-all.sql ${GITHUB_WORKSPACE}/infrastructure/database.sqlite
          yarn prisma db seed

      - name: Run test suite
        run: |
          yarn test
