name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.ts'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Setup the environment
        run: |
          echo PORT="3001" >> .env
          echo DATABASE_URL="file:${GITHUB_WORKSPACE}/infrastructure/database.sqlite" >> .env
          
      - name: Install dependencies
        run: yarn install
          
      - name: Setup the database & ORM
        run: |
          yarn prisma generate
          yarn prisma db push
      
      - name: Insert data into database
        run: |
          sqlite3 -init ${GITHUB_WORKSPACE}/infrastructure/sql/import-all.sql ${GITHUB_WORKSPACE}/infrastructure/database.sqlite
          yarn prisma db seed

      - name: Run eslint
        run: yarn run lint:ci

      - name: Run test suite
        run: yarn test:ci

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn
          
      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run lint:ci

  openapi-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install Swagger/OpenAPI CLI
        run: npm install -g @apidevtools/swagger-cli
      
      - name: Validation OpenAPI schema
        run: npx swagger-cli validate ${GITHUB_WORKSPACE}/openapi.yaml